# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: CICD & CFN
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      # Change this, as applicable to you
      KeyName: duong-udacity-west
      # Ubuntu Server 22.04 LTS
      ImageId: 'ami-0dc5e9ff792ec08e3'
      InstanceType: t3.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
